spring.application.name=sistema-taller

# Configuracion de la base de datos PostgreSQL
# Las credenciales se leen desde variables de entorno
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Configuracion de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.validation-timeout=3000

# Configuración de la base de datos PostgreSQL local
#spring.datasource.url=jdbc:postgresql://localhost:5432/mi_taller_bd
#spring.datasource.username=usuario
#spring.datasource.password=userpsql



